### PR TITLE
Remove colour assignment for 'Normal'

### PR DESCRIPTION
**Pull request by XiaochenCui**
Fixed a bug where the background color changed to gray in bash v4.3.46.

### CODE REVIEW

**Comment by agude** [comment]
I'll probably add a variable to set it later and leave it off by default, but this is will do in the meantime! Thanks!

**Comment by XiaochenCui** [comment]
Thanks for your eldar. It‘s pretty again.

**Comment by agude** [comment]
Hi @XiaochenCui:

I've added a commit to allow setting the text and background color. Everything should look exactly the same (assuming you don't set the new variables to something else). I've tested it with neovim, vim, and gvim and it looks good on my side, but please let me know if anything does change (by filling a bug) and I'll fix it!

**Comment by XiaochenCui** [comment]
Hi @agude:

I don't have gui vim installed and I try to set `g:eldar_term_background="Black"` in .vimrc in termial to test the eldar. But it failed with error `Pattern not found: eldar_term_background  = "Black"`. Because I am a novice vim, I do not know why the problem occurred.

**Pull request merged**
